language: php

php:
  - 5.6
  - 7.2

before_script:
  - composer self-update
  - composer require php-coveralls/php-coveralls
  - composer install --prefer-source --no-interaction

script:
  - mkdir -p build/logs
  - vendor/bin/phpunit --configuration phpunit.xml --coverage-clover build/logs/clover.xml
  - vendor/bin/behat --config behat.yml

after_success:
  - travis_retry php vendor/bin/php-coveralls -v
