site_name: Perú Consultas
site_url: https://giansalex.github.io/peru-consult
site_description: 'Perú Consultas · Información de DNI y RUC.'
site_author: 'Giancarlos Salas'

# Repository
repo_name: 'giansalex/peru-consult'
repo_url: 'https://github.com/giansalex/peru-consult'

nav:
    - Inicio: index.md
    - Dni: dni.md
    - Ruc: ruc.md
    - 'Usuario SOL': user-sol.md

# Configuration
theme:
  name: 'material'
  favicon: 'img/peru.png'
  logo: 'img/peru.png'
  include_search_page: false
  search_index_only: true
  static_templates:
    - 404.html
  language: 'es'
  palette:
    primary: 'Red'
    accent: 'Amber'

extra_css:
  - 'https://cdnjs.cloudflare.com/ajax/libs/prism/1.15.0/themes/prism-okaidia.min.css'
  - 'https://rawcdn.githack.com/markusressel/MkDocs-Material-Dark-Theme/7d9804adb85251a75696a3b24f7602e5df465e2a/docs/stylesheets/dark_theme.css'
  - 'https://rawcdn.githack.com/markusressel/MkDocs-Material-Dark-Theme/7d9804adb85251a75696a3b24f7602e5df465e2a/docs/stylesheets/codehilite.css'
extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/prism/1.15.0/prism.min.js'
  - 'https://cdnjs.cloudflare.com/ajax/libs/prism/1.15.0/components/prism-markup-templating.min.js'
  - 'https://cdnjs.cloudflare.com/ajax/libs/prism/1.15.0/components/prism-php.min.js'
  - 'https://cdnjs.cloudflare.com/ajax/libs/prism/1.15.0/components/prism-json.min.js'

extra:
  social:
    - icon: fontawesome/brands/github
      link: 'https://github.com/giansalex'
  author:
    github: giansalex
  disqus: 'peru-consult'

# Google Analytics
google_analytics:
  - 'UA-90097417-4'
  - 'auto'

plugins:
  - search
  - minify:
      minify_html: true

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      css_class: code
      use_pygments: false
      guess_lang: false
  - toc:
      permalink: true
