site_name: Perú Consultas
site_url: https://giansalex.github.io/peru-consult
site_description: 'Documentación de Perú Consultas, DNI - Reniec, RUC - Sunat'
site_author: 'Giancarlos Salas'

# Repository
repo_name: 'giansalex/peru-consult'
repo_url: 'https://github.com/giansalex/peru-consult'

pages:
    - Principal: index.md
    - Dni: dni.md
    - Ruc: ruc.md
    - 'Usuario SOL': user-sol.md

# Configuration
theme:
  name: 'material'
  favicon: 'img/peru.png'
  logo: 'img/peru.png'
  language: 'es'
  palette:
    primary: 'Red'
    accent: 'Indigo'

extra_css:
  - 'https://cdnjs.cloudflare.com/ajax/libs/prism/1.10.0/themes/prism-okaidia.min.css'
extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/prism/1.10.0/prism.min.js'
  - 'https://cdnjs.cloudflare.com/ajax/libs/prism/1.10.0/components/prism-php.min.js'
  - 'https://cdnjs.cloudflare.com/ajax/libs/prism/1.10.0/components/prism-json.min.js'

extra:
  social:
    - type: 'github'
      link: 'https://github.com/giansalex'
  author:
    github: giansalex
  disqus: 'peru-consult'

# Google Analytics
google_analytics:
  - 'UA-90097417-4'
  - 'auto'

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      css_class: code
      use_pygments: false
      guess_lang: false
  - toc:
      permalink: true
