name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: PHP Tests on ${{ matrix.operating-system }}
    runs-on: ${{ matrix.operating-system }}
    strategy:
      max-parallel: 2
      matrix:
        operating-system: [ubuntu-latest, windows-latest]
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 7.1
        extensions: mbstring
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress
    - name: Install React HTTP
      run: composer require react/http
    - name: Run PHPStan
      run: composer run-script lint:ci
    - name: Create test directory
      run: mkdir -p test-results/behat
      shell: bash
    - name: PHPUnit Tests
      run: vendor/bin/phpunit --coverage-clover clover.xml
      shell: bash
      env:
        MOCK_URL: ${{ secrets.MockServer }}
    - name: BDD Tests
      run: vendor/bin/behat --config behat.yml -f pretty -o std -f junit -o test-results/behat/
      shell: bash
    - name: Report code coverage
      uses: codecov/codecov-action@v1
      with:
        file: ./clover.xml
        flags: unittests
        name: codecov-peruconsult
      if: matrix.operating-system == 'ubuntu-latest'